-- Additive only: isolated from public and the user's existing application.
create table if not exists trading_bot.screening_runs(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references trading_bot.workspaces(id) on delete cascade,started_at timestamptz not null default now(),completed_at timestamptz,provider text not null,status text not null check(status in('running','completed','failed')),error text);
create table if not exists trading_bot.stock_candidates(id uuid primary key default gen_random_uuid(),run_id uuid not null references trading_bot.screening_runs(id) on delete cascade,workspace_id uuid not null references trading_bot.workspaces(id) on delete cascade,symbol text not null,company text not null,industry text not null,score numeric not null check(score between 0 and 100),metrics jsonb not null,entry_plan jsonb not null,evidence jsonb not null,price_as_of timestamptz not null,created_at timestamptz not null default now());
create table if not exists trading_bot.positions(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references trading_bot.workspaces(id) on delete cascade,candidate_id uuid references trading_bot.stock_candidates(id) on delete set null,symbol text not null,company text not null,industry text not null,quantity numeric not null check(quantity>0),purchase_price numeric not null check(purchase_price>0),target_price numeric,invalidation_price numeric,status text not null default 'open' check(status in('open','closed')),opened_at timestamptz not null default now(),closed_at timestamptz);
create table if not exists trading_bot.position_alerts(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references trading_bot.workspaces(id) on delete cascade,position_id uuid not null references trading_bot.positions(id) on delete cascade,severity text not null check(severity in('info','warning','critical')),signal_type text not null,message text not null,evidence jsonb not null default'[]',observed_at timestamptz not null,acknowledged_at timestamptz);
create index if not exists runs_workspace_idx on trading_bot.screening_runs(workspace_id,started_at desc);create index if not exists candidates_workspace_idx on trading_bot.stock_candidates(workspace_id,created_at desc);create index if not exists positions_workspace_idx on trading_bot.positions(workspace_id,status);create index if not exists alerts_workspace_idx on trading_bot.position_alerts(workspace_id,observed_at desc);
alter table trading_bot.screening_runs enable row level security;alter table trading_bot.stock_candidates enable row level security;alter table trading_bot.positions enable row level security;alter table trading_bot.position_alerts enable row level security;
create policy "owner screening" on trading_bot.screening_runs for all to authenticated using(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid()))) with check(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid())));
create policy "owner candidates" on trading_bot.stock_candidates for all to authenticated using(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid()))) with check(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid())));
create policy "owner positions" on trading_bot.positions for all to authenticated using(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid()))) with check(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid())));
create policy "owner alerts" on trading_bot.position_alerts for all to authenticated using(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid()))) with check(exists(select 1 from trading_bot.workspaces w where w.id=workspace_id and w.user_id=(select auth.uid())));
grant select,insert,update,delete on trading_bot.screening_runs,trading_bot.stock_candidates,trading_bot.positions,trading_bot.position_alerts to authenticated;
